apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygments-server
  namespace: tool-notwikilambda
  labels:
    name: pygments-server
spec:
  selector:
    matchLabels:
      name: pygments-server
  template:
    metadata:
      labels:
        name: pygments-server
    spec:
      containers:
        - name: pygments-server
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-web:latest
          command: [ "../venv/bin/gunicorn", "--workers=4", "--bind=:7879", "app:app" ]
          ports:
            - containerPort: 7879
              name: pygments
              protocol: TCP
          workingDir: /data/project/notwikilambda/www/python/src
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m" # less than the default, to avoid hitting the quota
            limits:
              cpu: "100m" # less than the default, to avoid hitting the quota
          volumeMounts:
            - name: src
              # venvs are not position-independent, so mount under the original path
              mountPath: '/data/project/notwikilambda/www/python'
      volumes:
        - name: src
          hostPath:
            path: '/data/project/notwikilambda/www/python'
