apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-evaluator
  namespace: tool-notwikilambda
  labels:
    name: function-evaluator
spec:
  selector:
    matchLabels:
      name: function-evaluator
  template:
    metadata:
      labels:
        name: function-evaluator
        networking: internal
    spec:
      automountServiceAccountToken: false
      containers:
        - name: function-evaluator
          image: docker-registry.tools.wmflabs.org/toolforge-node12-sssd-web:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              git pull --recurse-submodules
              npm ci
              exec npm start
          ports:
            - containerPort: 6927
              name: evaluator
              protocol: TCP
          workingDir: /srv/function-evaluator
          env:
            - name: HOME
              value: /srv/function-evaluator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m" # less than the default, to avoid hitting the quota
            limits:
              cpu: "200m" # less than the default, to avoid hitting the quota
          volumeMounts:
            - name: src
              mountPath: '/srv/function-evaluator'
          startupProbe:
            httpGet:
              path: /_info/name
              port: evaluator
            failureThreshold: 40
            periodSeconds: 15
            # gives the container 15 s * 40 = 10 minutes to update, install and start
      volumes:
        - name: src
          hostPath:
            path: '/data/project/notwikilambda/www/js/function-evaluator'
