apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-orchestrator
  namespace: tool-notwikilambda
  labels:
    name: function-orchestrator
    toolforge: tool
spec:
  selector:
    matchLabels:
      name: function-orchestrator
      toolforge: tool
  template:
    metadata:
      labels:
        name: function-orchestrator
        toolforge: tool
        networking: internal
    spec:
      automountServiceAccountToken: false
      containers:
        - name: function-orchestrator
          image: docker-registry.tools.wmflabs.org/toolforge-node10-sssd-web:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              while true; do
                  git pull --recurse-submodules
                  npm ci
                  timeout 12h npm start
                  if (($? != 124)); then
                      break
                  fi
              done
          ports:
            - containerPort: 6254
              name: orchestrator
              protocol: TCP
          workingDir: /data/project/notwikilambda/www/js/function-orchestrator
          env:
            - name: HOME
              value: /data/project/notwikilambda
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m" # less than the default, to avoid hitting the quota
            limits:
              cpu: "200m" # less than the default, to avoid hitting the quota
